FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
WORKDIR /api

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install fastapi
RUN pip install uvicorn[standard]
RUN pip install pydantic
RUN pip install starlette
